### PR TITLE
Make GTK2 activities run properly outside Sugar.

### PR DESCRIPTION
**Pull request by icarito**
- Proper themes and scaling overriding XSETTINGS daemon
- Set activity icon
- Scale activity window in accordance to workarea
- Find acitivity root

### CODE REVIEW

**Comment by icarito** [comment]
Can't we merge this?

**Comment by samdroid-apps** [comment]
Didn't you already merge this?

**Comment by icarito** [comment]
No, this is completely different. Without this, GTK2 activities look horrible outside Sugar. There is a very similar (merged) pull request in sugar-toolkit-gtk3 - this one is the equivalent for sugar-toolkit. :-)

**Comment by samdroid-apps** [comment]
I will test this soon.  I just discovered that I don't have the pygobject headers installed.  It will miss today unstable sorry.

**Comment by samdroid-apps** [comment]
I will test this soon.  I just discovered that I don't have the pygobject headers installed.  It will miss today unstable sorry.

**Comment by icarito** [comment]
I don't think you need headers, I think if you use sugar-build you can use `osbuild shell`...

**Comment by icarito** [comment]
I just installed osbuild and can give a way to test this patch:
- run `osbuild shell`
- `cd turtleart`
- `sugar-activity`

Without this patch it will look really bad.

**Comment by davelab6** [comment]
@samdroid-apps when do you plan to cut the next unstable release?

**Comment by samdroid-apps** [comment]
@icarito sorry about not reviewing this, I will get it done for tommorow

@davelab6 I have some time tomorrow to do a release.  I'm going to make some tarballs with some webkit2 patches as well - so that we can test a sugar without a webkit1 dep.

**Pull request merged**
